version: '3.7'
services:
  web:
    restart: always
    container_name: web
    build: ./services/web
    ports:
      - 5000:5000
    entrypoint: ['gunicorn', '-w', '7', '-b', '0.0.0.0:5000', 'dev_wsgi']
