version: '3.7'
services:
  web:
    restart: always
    container_name: web
    build: ./services/web
    expose:
      - 5000
    entrypoint: ['gunicorn', '-w', '7', '-b', '0.0.0.0:5000', 'wsgi']
  nginx:
    restart: always
    container_name: nginx
    build: ./services/reverse_proxy
    depends_on:
      - web
    ports:
      - 4443:443
