version: '3.7'
services:
  web_application:
    restart: always
    container_name: web_application
    build: ./services/web_application
    image: web_application:web_application
    environment:
      - SECRET_KEY=this_is_my_global_secret_key_change_it
      - WTF_CSRF_SECRET_KEY=wtf_csrf_secret_token_key_change_it
  reverse_proxy:
    restart: always
    container_name: reverse_proxy
    build: ./services/reverse_proxy
    image: reverse_proxy:reverse_proxy
    depends_on:
      - web_application
    ports:
      - 443:443
      - 80:80
